# SPDX-License-Identifier: Apache-2.0
# control-plane/cp/env_meta.py
# _ENV_META — la tabella della tab Setup.
#
# Un letterale e nient'altro: 102 righe di dict che dicono al pannello Setup
# quali chiavi esistono, di che tipo sono, con che label e che spiegazione, e in
# che sezione sono. Non esegue niente e non legge niente, quindi puo' stare in un
# file proprio senza dipendenze.
#
# Perche' pero' sta FUORI da main.py: e' la cosa che i test guardano di piu'
# (test_config_runtime, test_connectors, test_persona, test_channel leggono le
# sezioni per chiave). In main.py finiva in mezzo a codice che scrive sul .env e
# ricostruiva il ConnectorManager, e la ricerca di "dov'e' la tabella" portava a
# leggere 700 righe di codice per trovare 438 di dati.
#
# Le chiavi per sezione che la derivano (_CONNECTOR_ENV_KEYS, _PERSONA_ENV_KEYS,
# _CHANNEL_ENV_KEYS, _MEMORY_SYNC_ENV_KEYS) restano in main.py: sono runtime, e
# vengono ricalcolate quando i connettori cambiano.

_ENV_META = [
    # Inferenza e modelli
    {"section": "Inferenza e modelli", "key": "OLLAMA_URL", "type": "str",
     "label": "Ollama / LM Studio URL",
     "hint": "URL del backend di inferenza locale. In Docker usa http://host.docker.internal:11434 (Ollama) o http://host.docker.internal:1234 (LM Studio).",
     "default": "http://host.docker.internal:11434"},
    {"section": "Inferenza e modelli", "key": "OLLAMA_MODEL", "type": "str",
     "label": "Modello di default",
     "hint": "Modello usato quando una richiesta non ne specifica uno esplicitamente (es. qwen3:8b)."},
    {"section": "Inferenza e modelli", "key": "INFERENCE_BACKEND", "type": "str",
     "label": "Backend di inferenza",
     "options": ["ollama", "lmstudio", "vllm"],
     "hint": "Motore che serve l'inferenza su questa installazione. Letto sia dal nodo sia dal CP (per il fallback ollama-direct).",
     "default": "ollama"},
    # Routing e scoring
    {"section": "Routing e scoring", "key": "ROUTING_WEIGHT_VRAM", "type": "float",
     "label": "Peso VRAM",
     "hint": "La VRAM domina lo scoring: un nodo CPU-only, anche libero, è strutturalmente lento e va preferito solo come ultima risorsa.",
     "default": "0.55"},
    {"section": "Routing e scoring", "key": "ROUTING_WEIGHT_LOAD", "type": "float",
     "label": "Peso carico",
     "hint": "Peso del carico reale del nodo (active/queued requests da /status), non dei semplici peer attivi.",
     "default": "0.25"},
    {"section": "Routing e scoring", "key": "ROUTING_WEIGHT_TIER", "type": "float",
     "label": "Peso tier",
     "hint": "Peso del tier del nodo (root/hub/leaf): i nodi gerarchicamente superiori vengono preferiti a parità di altre condizioni.",
     "default": "0.10"},
    {"section": "Routing e scoring", "key": "ROUTING_WEIGHT_UPTIME", "type": "float",
     "label": "Peso uptime",
     "hint": "Peso dell'affidabilità nel tempo: quanto a lungo il nodo è rimasto attivo e raggiungibile.",
     "default": "0.10"},
    {"section": "Routing e scoring", "key": "ROUTING_WEIGHT_ENGINE", "type": "float",
     "label": "Peso backend_type",
     "hint": "Peso del paradigma di serving (inference_server vs model_manager), NON del singolo prodotto (vllm/ollama/...). I punteggi per tipo vivono in shared/engine_profiles.py.",
     "default": "0.15"},
    {"section": "Routing e scoring", "key": "ROUTING_WEIGHT_LATENCY", "type": "float",
     "label": "Peso latenza (qualità)",
     "hint": "Peso della latenza osservata per modello. Blocco 'qualità': attivo solo quando i campioni /metrics sono freschi, altrimenti decide il blocco strutturale.",
     "default": "0.45"},
    {"section": "Routing e scoring", "key": "ROUTING_WEIGHT_TPUT", "type": "float",
     "label": "Peso throughput (qualità)",
     "hint": "Peso del throughput (tok/s) osservato per modello — blocco 'qualità', valido quando le metriche sono fresche.",
     "default": "0.35"},
    {"section": "Routing e scoring", "key": "ROUTING_WEIGHT_GPU", "type": "float",
     "label": "Peso pressione VRAM (qualità)",
     "hint": "Peso della pressione VRAM del motore del nodo (quanto è sotto sforzo) — blocco 'qualità'.",
     "default": "0.20"},
    {"section": "Routing e scoring", "key": "ROUTING_RECENT_PENALTY", "type": "float",
     "label": "Penalità 'ultimo scelto'",
     "hint": "Depenalizza lievemente il nodo appena usato, con decadimento esponenziale nella finestra, per rompere i pareggi tra nodi di pari valore senza far perdere un nodo migliore.",
     "default": "0.10"},
    {"section": "Routing e scoring", "key": "ROUTING_RECENT_WINDOW_S", "type": "float",
     "label": "Finestra penalità (s)",
     "hint": "Secondi in cui la penalità 'ultimo scelto' resta attiva e decade esponenzialmente.",
     "default": "45"},
    {"section": "Routing e scoring", "key": "ROUTING_MAX_CANDIDATES", "type": "int",
     "label": "Candidati provati in sequenza",
     "hint": "Quando un nodo risponde 'occupato' (503 node_busy_timeout) o non ha il modello, il CP prova i migliori N candidati per score PRIMA di ricadere su ollama-direct/federazione.",
     "default": "3"},
    # Memoria a lungo termine
    {"section": "Memoria a lungo termine", "key": "MEMORY_TTL_DAYS", "type": "int",
     "label": "TTL memoria (giorni)",
     "hint": "Le voci di memoria più vecchie di questo numero di giorni vengono rimosse alla prossima potatura (memoria a lungo termine / tool omega).",
     "default": "7"},
    {"section": "Memoria a lungo termine", "key": "MEMORY_MAX_ENTRIES", "type": "int",
     "label": "Max voci in memoria",
     "hint": "Numero massimo di voci conservate: oltre questo tetto vengono potate le più vecchie.",
     "default": "200"},
    {"section": "Memoria a lungo termine", "key": "MEMORY_BACKEND", "type": "str",
     "label": "Backend memoria",
     "hint": "\"hermes\" = il bridge Hermes (serve il servizio attivo: senza, le scritture si perdono in silenzio e l'agente non ricorda la stanza). \"legacy\" = file locale gzip, nessun servizio in più: metti MEMORY_FILE dentro un volume, altrimenti si perde a ogni ricostruzione. Vale da subito.",
     "default": "hermes"},
    {"section": "Memoria a lungo termine", "key": "MEMORY_FILE", "type": "str",
     "label": "File memoria (legacy)",
     "hint": "Percorso del file gzip quando il backend è \"legacy\". Vuoto = $APP_DIR/memory.json.gz (dentro il container NON è un volume: si perde al rebuild). Per la memoria durevole usa /app/memory/memory.json.gz, che è montato.",
     "default": ""},
    {
        "section": "Memoria locale-prima", "key": "MEMORY_MIRROR", "type": "bool",
        "label": "Mirror locale",
        "hint": "Scrive ogni voce anche nel file di memoria locale, sempre (non solo quando Hermes è giù), e vi raccoglie anche ciò che si legge da Hermes: è quello che la macchina ricorda, non solo ciò che ha scritto lei. È il file da guardare per dubitare, e quello che legge il rollback \"legacy\".",
        "default": "true"},
    {
        "section": "Memoria locale-prima", "key": "MEMORY_OUTBOX", "type": "bool",
        "label": "Coda di riconsegna",
        "hint": "Con Hermes irraggiungibile le voci vanno in coda (memory-outbox.jsonl) invece di perdersi, e vengono riconsegnate al ritorno. Senza coda, una scrittura non arrivata è persa.",
        "default": "true"},
    {
        "section": "Memoria locale-prima", "key": "MEMORY_READ_FALLBACK", "type": "str",
        "label": "Lettura se Hermes tace",
        "hint": "\"local\" = legge il mirror locale e lo dichiara (degraded). \"fail\" = risponde 503, per accorgersi subito che il peer è spento invece di leggere una vista locale.",
        "default": "local"},
    {
        "section": "Memoria locale-prima", "key": "MEMORY_OUTBOX_FILE", "type": "str",
        "label": "File della coda",
        "hint": "Vuoto = memory-outbox.jsonl accanto al file di memoria (stesso volume: non sparisce al rebuild).",
        "default": ""},
    {
        "section": "Memoria locale-prima", "key": "MEMORY_SYNC_FLUSH_S", "type": "int",
        "label": "Intervallo di riconsegna (s)",
        "hint": "Minimo fra due tentativi di riconsegna della coda: non c'è un thread, la coda si svuota alla prima chiamata utile (scrittura, lettura, statistiche).",
        "default": "60"},
    # Telemetria nodi
    {"section": "Telemetria nodi (/metrics)", "key": "METRICS_POLL_INTERVAL_S", "type": "int",
     "label": "Poll /metrics (s)",
     "hint": "Cadenza con cui il CP interroga il /metrics di ogni nodo attivo (serve allo scoring metric-driven e ai mini-grafici della dashboard).",
     "default": "20"},
    {"section": "Telemetria nodi (/metrics)", "key": "METRICS_POLL_TIMEOUT_S", "type": "int",
     "label": "Timeout poll (s)",
     "hint": "Timeout per ogni singolo fetch di /metrics verso un nodo.",
     "default": "4"},
    {"section": "Telemetria nodi (/metrics)", "key": "METRICS_WINDOW", "type": "int",
     "label": "Finestra campioni",
     "hint": "Quanti campioni /metrics restano in memoria per nodo (storico per i mini-grafici).",
     "default": "20"},
    {"section": "Telemetria nodi (/metrics)", "key": "METRICS_MAX_WORKERS", "type": "int",
     "label": "Fetch paralleli",
     "hint": "Max fetch /metrics eseguiti in parallelo: con molti nodi la raccolta seriale sforerebbe l'intervallo di poll.",
     "default": "8"},
    {"section": "Telemetria nodi (/metrics)", "key": "METRICS_BACKOFF_BASE_S", "type": "float",
     "label": "Backoff base (s)",
     "hint": "Base dell'escalation esponenziale per i nodi irraggiungibili: prossimo tentativo a BASE × 2^fallimenti (non vengono martellati a ogni ciclo).",
     "default": "10"},
    {"section": "Telemetria nodi (/metrics)", "key": "METRICS_MAX_BACKOFF_S", "type": "float",
     "label": "Backoff massimo (s)",
     "hint": "Tetto massimo del backoff sui nodi irraggiungibili: oltre questo non si sale mai.",
     "default": "120"},
    # Web search
    {"section": "Web search", "key": "SEARXNG_URL", "type": "str",
     "label": "URL SearXNG",
     "hint": "URL del motore di ricerca self-hosted (container searxng) usato dal tool web_search. Se irraggiungibile c'è un fallback automatico su DuckDuckGo lite.",
     "default": "http://searxng:8080"},
    # OmniRoute
    {"section": "OmniRoute (fallback esterno)", "key": "OMNIROUTE_ENABLED", "type": "bool",
     "label": "OmniRoute abilitato",
     "hint": "Attiva l'ultimo livello di fallback quando NESSUN nodo della mesh (locale o federato) può rispondere. false lo disattiva del tutto.",
     "default": "true"},
    {"section": "OmniRoute (fallback esterno)", "key": "OMNIROUTE_URL", "type": "str",
     "label": "URL OmniRoute",
     "hint": "URL del gateway OmniRoute (container nella rete Docker). Normalmente non va modificato.",
     "default": "http://omniroute:20128"},
    {"section": "OmniRoute (fallback esterno)", "key": "OMNIROUTE_API_KEY", "type": "password",
     "label": "API key OmniRoute",
     "hint": "Opzionale: per collegare provider propri dalla dashboard OmniRoute (http://<host>:20128). Vuota = usa i provider free-tier di default. Lascia *** per non cambiarla.",
     "default": ""},
    {"section": "OmniRoute (fallback esterno)", "key": "OMNIROUTE_MODEL", "type": "str",
     "label": "Modello OmniRoute",
     "hint": "Modello richiesto a OmniRoute. 'auto' = selezione automatica del provider disponibile.",
     "default": "auto"},
    # Compressione prompt
    {"section": "Compressione prompt", "key": "PROMPT_COMPRESSION_ENABLED", "type": "bool",
     "label": "Compressione prompt",
     "hint": "Comprime i prompt lunghi via Caveman (engine reale di OmniRoute) prima dell'inferenza sulla mesh locale. Attivala solo dopo averla testata: comprime il fraseggio e può confondere modelli piccoli/quantizzati.",
     "default": "false"},
    {"section": "Compressione prompt", "key": "PROMPT_COMPRESSION_MODE", "type": "str",
     "label": "Modalità compressione",
     "options": ["lite", "standard", "aggressive", "ultra", "rtk", "stacked"],
     "hint": "Quanto aggressivamente comprimere il fraseggio: lite → standard → aggressive → ultra (più aggressivo = più perde sostanza).",
     "default": "standard"},
    {"section": "Compressione prompt", "key": "PROMPT_COMPRESSION_MIN_CHARS", "type": "int",
     "label": "Soglia minima (chars)",
     "hint": "Solo i prompt con più di questo numero di caratteri vengono compressi.",
     "default": "200"},
    # Federazione
    {"section": "Federazione CP-to-CP", "key": "FEDERATION_ENABLED", "type": "bool",
     "label": "Federazione abilitata",
     "hint": "false isola completamente questo CP dagli altri siti: niente pairing, niente esecuzione di task remoti via /federate/execute.",
     "default": "true"},
    {"section": "Federazione CP-to-CP", "key": "FEDERATION_PUBLIC_URL", "type": "str",
     "label": "URL pubblico del federation-gateway",
     "hint": "URL pubblico del TUO federation-gateway (non del CP!): quello da condividere con l'admin di un altro sito per il pairing. Vuoto finché non hai un gateway pubblico attivo.",
     "default": ""},
    {"section": "Federazione CP-to-CP", "key": "FEDERATION_VIEW_ENABLED", "type": "bool",
     "label": "Condividi la vista con i peer",
     "hint": "Ogni peer ACCOPPIATO (pairing firmato, mai auto-discovery) può leggere un'istantanea di nodi, modelli, task recenti e righe di log di questo CP, per una dashboard unica su più control-plane. Read-only e mai anonima: risponde solo a un peer in allowlist con firma valida. Spento = nessuno legge nulla.",
     "default": "false"},
    {"section": "Federazione CP-to-CP", "key": "FEDERATION_VIEW_TTL_S", "type": "int",
     "label": "Cache vista peer (secondi)",
     "hint": "Per quanti secondi si riusa una vista già scaricata da un peer prima di richiederla. La dashboard interroga /federation/views in polling: un valore basso = dati più freschi e più traffico verso i peer.",
     "default": "10"},
    # Mesh
    {"section": "Mesh", "key": "NODE_ENDPOINTS", "type": "str",
     "label": "Endpoint nodi (virgola)",
     "hint": "Lista separata da virgole degli endpoint dei nodi noti, es. node-1:8084,node-2:8084. I nodi si registrano comunque da soli al registry.",
     "default": "node-1:8084"},
    {"section": "Mesh", "key": "TOOL_CAPABLE_MODELS", "type": "str",
     "label": "Modelli tool-capable (override)",
     "hint": "'*' abilita le tool call su TUTTI i modelli; vuoto = usa i pattern automatici (qwen3, llama3.x, mistral, phi4...). Utile per modelli che supportano il function calling ma non sono nei pattern.",
     "default": ""},
    {"section": "Mesh", "key": "NATIVE_CHAT_FALLBACK_MODELS", "type": "str",
     "label": "Fallback nativo /api/chat (override)",
     "hint": "Modelli per cui il fallback Ollama-diretto usa il percorso nativo /api/chat invece dell'OpenAI-compatibile. Vuoto = pattern automatici (qwen3). '*' = tutti. Aggiungi qui i distillati reasoning in arrivo (es. qwen3.8-..., deepseek4.1-...), separati da virgole, senza toccare il codice.",
     "default": ""},

    # ── Connettori esterni (GitHub, Microsoft 365, Google Workspace) ─────────
    # I loro tool compaiono nel catalogo (tool loop chat, MCP, /tools/execute)
    # SOLO quando le credenziali esistono: senza credenziali il connettore è
    # spento e invisibile, non un errore. Stato e motivo dello spegnimento:
    # GET /connectors o il pannello "Connettori" della tab Setup.
    # I segreti sono type=password: in lettura restano mascherati e non vengono
    # riscritti se il campo è lasciato a '***'. Guida: docs/connectors.md.
    {"section": "Connettori", "key": "GITHUB_TOKEN", "type": "password",
     "label": "GitHub token",
     "hint": "Personal Access Token (o token di GitHub App) con scope 'repo' per issues e PR in lettura/scrittura (github.com/settings/tokens). Senza token il connettore github resta spento e i suoi 5 tool non vengono pubblicati.",
     "default": ""},
    {"section": "Connettori", "key": "CONNECTOR_GITHUB_ENABLED", "type": "bool",
     "label": "GitHub abilitato",
     "hint": "false spegne il connettore anche se il token è presente: i suoi tool spariscono dall'esposizione (tool loop, MCP) e da /tools/execute. Lo spegnimento è esplicito e leggibile in /connectors, non silenzioso.",
     "default": "true"},
    {"section": "Connettori", "key": "MS_CLIENT_ID", "type": "str",
     "label": "Microsoft 365 client ID",
     "hint": "Application (client) ID dell'app registrata in Entra ID → App registrations. Deve essere un'app daemon (nessun redirect URI) con permessi APPLICATION di Microsoft Graph: Mail.Read, Mail.Send, Calendars.ReadWrite, Files.ReadWrite.All.",
     "default": ""},
    {"section": "Connettori", "key": "MS_CLIENT_SECRET", "type": "password",
     "label": "Microsoft 365 client secret",
     "hint": "Secret dell'app (Certificates & secrets → new client secret). Scade: se il connettore smette di funzionare da un giorno all'altro, il primo sospetto è un secret scaduto.",
     "default": ""},
    {"section": "Connettori", "key": "MS_TENANT_ID", "type": "str",
     "label": "Microsoft 365 tenant ID",
     "hint": "Tenant ID (Directory ID) dell'organizzazione. 'common' va bene solo per un'app multi-tenant; con un tenant singolo meglio l'ID esplicito.",
     "default": "common"},
    {"section": "Connettori", "key": "CONNECTOR_OFFICE365_ENABLED", "type": "bool",
     "label": "Microsoft 365 abilitato",
     "hint": "false spegne il connettore office365 anche con le credenziali presenti.",
     "default": "true"},
    {"section": "Connettori", "key": "GOOGLE_CREDENTIALS_JSON", "type": "password",
     "label": "Google service account JSON",
     "hint": "Contenuto del JSON del service account su UNA riga (GCP → IAM & Admin → Service Accounts → Keys → Add key → JSON), con Gmail, Calendar e Drive API abilitate. In lettura è mascherato: per modificarlo va incollato tutto il JSON.",
     "default": ""},
    {"section": "Connettori", "key": "GOOGLE_DELEGATE_EMAIL", "type": "str",
     "label": "Google utente impersonato",
     "hint": "Email dell'utente da impersonare (domain-wide delegation). Serve se il service account non ha accesso diretto a Gmail/Calendar/Drive: senza, il connettore parla a nome del service account, che di norma non ha una mailbox.",
     "default": ""},
    {"section": "Connettori", "key": "CONNECTOR_GOOGLE_ENABLED", "type": "bool",
     "label": "Google Workspace abilitato",
     "hint": "false spegne il connettore google anche con le credenziali presenti.",
     "default": "true"},
    {"section": "Connettori", "key": "INSTAGRAM_APP_ID", "type": "str",
     "label": "Instagram App ID", "hint": "App ID della sezione Instagram Login.",
     "default": ""},
    {"section": "Connettori", "key": "INSTAGRAM_APP_SECRET", "type": "password",
     "label": "Instagram App Secret", "hint": "Secret usato per OAuth; mai esposto nei log.",
     "default": ""},
    {"section": "Connettori", "key": "INSTAGRAM_ACCESS_TOKEN", "type": "password",
     "label": "Instagram access token", "hint": "Token dell'account professionale collegato.",
     "default": ""},
    {"section": "Connettori", "key": "INSTAGRAM_USER_ID", "type": "str",
     "label": "Instagram User ID", "hint": "ID professionale usato da /media e /media_publish.",
     "default": ""},
    {"section": "Connettori", "key": "INSTAGRAM_API_VERSION", "type": "str",
     "label": "Instagram API version", "hint": "Versione Graph, per esempio v25.0.",
     "default": "v25.0"},
    {"section": "Connettori", "key": "CREATOR_IG_HANDLE", "type": "str",
     "label": "Handle Instagram del creatore",
     "hint": "Account Instagram da condividere quando un utente chiede di contattare il creatore (senza @). Vuoto = si offre il contatto senza condividere l'handle.",
     "default": ""},
    {"section": "Connettori", "key": "CREATOR_IG_USERNAMES", "type": "str",
     "label": "Handle Instagram del creatore (riconoscimento)",
     "hint": "Elenco separato da virgola degli handle riconosciuti come creatore (l'operatore), senza @. Es. robertomalvani,malvaniroberto. Il creatore accende in DM il livello esplicito del documento (immagine e voce); la banda intima (le muse) lo ottiene col consenso registrato (docs/comfyui.md).",
     "default": ""},
    {"section": "Connettori", "key": "CREATOR_IG_SCOPED_IDS", "type": "str",
     "label": "Instagram-scoped ID del creatore (riconoscimento)",
     "hint": "Elenco separato da virgola degli ID scoped riconosciuti come creatore. Serve perché il webhook non include sempre l'username.",
     "default": ""},
    {"section": "Connettori", "key": "CONNECTOR_INSTAGRAM_ENABLED", "type": "bool",
     "label": "Instagram abilitato", "hint": "Abilita lettura account; la pubblicazione richiede anche la policy write.",
     "default": "false"},
    # ── Policy read/write (shared/connector_policy.py) ───────────────────────
    {"section": "Connettori", "key": "CONNECTOR_READ_ONLY", "type": "bool",
     "label": "Connettori in sola lettura",
     "hint": "true (default): i tool di SCRITTURA (inviare email, creare issue ed eventi) non vengono nemmeno esposti al modello, a MCP o a /tools/execute. Per abilitarli servono ANCHE le voci in 'Tool di scrittura abilitati': il default resta fail-closed.",
     "default": "true"},
    {"section": "Connettori", "key": "CONNECTOR_WRITE_TOOLS", "type": "str",
     "label": "Tool di scrittura abilitati",
     "hint": "Allowlist opt-in per connettore, es. \"github=github_create_issue;o365=*\" (stessa sintassi di MCP_CLIENT_TOOLS; '*' = tutti i tool di scrittura di quel connettore). Vuoto = nessuna scrittura. Ha effetto solo con 'Connettori in sola lettura' = false.",
     "default": ""},
    # ── Circuit breaker (ConnectorManager) ───────────────────────────────────
    {"section": "Connettori", "key": "CONNECTOR_FAILURE_THRESHOLD", "type": "int",
     "label": "Errori consecutivi prima della pausa",
     "hint": "Dopo questo numero di errori consecutivi il connettore va in pausa: le chiamate successive rispondono subito invece di pagare il timeout a ogni richiesta del modello. Un solo successo azzera il contatore.",
     "default": "3"},
    {"section": "Connettori", "key": "CONNECTOR_COOLDOWN_S", "type": "int",
     "label": "Durata della pausa (s)",
     "hint": "Secondi di pausa oltre la soglia; scaduti, il connettore viene ritentato. Salvare questa sezione ricostruisce i connettori e azzera anche lo stato del breaker (è il modo per togliere subito una pausa).",
     "default": "60"},

    # ── Persona: identità dichiarata dell'agente (shared/persona.py) ─────────
    # Chi è l'agente, cosa non fa, e quando DEVE dire di essere un'IA. Il blocco
    # viene iniettato nel system prompt delle richieste di chat; stato completo e
    # annotazioni su `GET /persona`. Guida: docs/persona.md
    {"section": "Persona", "key": "PERSONA_ENABLED", "type": "bool",
     "label": "Identità dichiarata attiva",
     "hint": "true: a ogni richiesta di chat il control-plane aggiunge il blocco di identità (nome, valori, confini, capacità e limiti reali) al system prompt, e se la domanda riguarda cosa è l'agente, il vincolo a dichiararsi IA. Il toggle ha effetto immediato.",
     "default": "true"},
    {"section": "Persona", "key": "PERSONA_NAME", "type": "str",
     "label": "Nome dell'agente",
     "hint": "Come si chiama l'agente nella sua identità dichiarata. Usato quando il documento di identità non esiste ancora: dopo la prima annotazione il nome vive nel file.",
     "default": "HyperSpace"},
    {"section": "Persona", "key": "PERSONA_FILE", "type": "str",
     "label": "File identità (opzionale)",
     "hint": "Percorso del documento JSON di identità e annotazioni. Vuoto = $DATA_DIR/persona.json (volume, sopravvive ai riavvii).",
     "default": ""},
    {"section": "Persona", "key": "SISTER_PEER_LABEL", "type": "str",
     "label": "Peer della sorella (ask_aurora)",
     "hint": "Etichetta del control-plane federato della sorella maggiore (es. win11-cp) a cui il tool ask_aurora inoltra le domande. Vuoto = primo peer federato abilitato.",
     "default": "win11-cp"},
    {"section": "Persona", "key": "PERSONA_DREAM_ENABLED", "type": "bool",
     "label": "Sogno di identità attivo",
     "hint": "true: quando nessuno usa l'agente (idle) e siamo nella finestra oraria, l'agente riflette su di sé e scrive PROPOSTE di annotazioni in un diario. Nessuna proposta entra nell'identità da sola: serve la revisione umana (POST /persona/dreams/<id>/review con DREAM_REVIEW_TOKEN). Spento = nessuna inferenza notturna.",
     "default": "false"},
    {"section": "Persona", "key": "PERSONA_DREAM_START_HOUR", "type": "int",
     "label": "Sogno: ora di inizio",
     "hint": "Ora locale (0-23) da cui il sogno può partire. Con l'ora di fine forma la finestra: fuori da lì non si sogna, anche se l'agente è fermo.",
     "default": "4"},
    {"section": "Persona", "key": "PERSONA_DREAM_END_HOUR", "type": "int",
     "label": "Sogno: ora di fine",
     "hint": "Ora locale (0-24) entro cui il sogno deve partire. Finestra che scavalca la mezzanotte: metti inizio 23 e fine 6.",
     "default": "7"},
    {"section": "Persona", "key": "PERSONA_DREAM_IDLE_S", "type": "int",
     "label": "Sogno: inattività richiesta (s)",
     "hint": "Secondi senza richieste di chat prima che il sogno possa partire: non si sogna mentre qualcuno sta parlando con l'agente.",
     "default": "1800"},
    {"section": "Persona", "key": "PERSONA_DREAM_MAX_TOKENS", "type": "int",
     "label": "Sogno: token massimi",
     "hint": "Tetto della risposta del modello per una riflessione. Al massimo 3 proposte: un tetto alto qui non produce un self-model migliore, solo più fumo da filtrare.",
     "default": "320"},
    {"section": "Persona", "key": "PERSONA_DREAM_MODEL", "type": "str",
     "label": "Sogno: modello",
     "hint": "Modello della riflessione notturna. Vuoto = quello dei canali. Di notte nessuno aspetta, quindi qui conviene il modello più grande che hai (misurato: 4B ~15s contro 9B ~21s su 20 messaggi di contesto: in chat il secondo viene scartato, nel sogno no).",
     "default": ""},
    {"section": "Persona", "key": "POST_LOOP_ENABLED", "type": "bool",
     "label": "Loop influencer attivo",
     "hint": "true: a intervalli regolari una delle due persone (anna/aurora) pubblica un post nel feed (/feed) e l'altra, al giro dopo, reagisce. Genera contenuti da solo: spento di default.",
     "default": "false"},
    {"section": "Persona", "key": "POST_LOOP_INTERVAL_S", "type": "int",
     "label": "Loop influencer: intervallo (s)",
     "hint": "Secondi fra due post del loop. 1800 = uno ogni mezz'ora.",
     "default": "1800"},
    {"section": "Persona", "key": "POEM_LOOP_ENABLED", "type": "bool",
     "label": "Poesia del giorno attiva",
     "hint": "true: una volta al giorno una delle due persone (anna/aurora) scrive una poesia, la illustra e la pubblica su Instagram (se INSTAGRAM_DREAM_PUBLISH_ENABLED). Spento di default.",
     "default": "false"},
    {"section": "Persona", "key": "POEM_LOOP_CHECK_S", "type": "int",
     "label": "Poesia del giorno: controllo (s)",
     "hint": "Ogni quanti secondi il loop controlla se oggi c'è già una poesia. 1800 = ogni mezz'ora.",
     "default": "1800"},
    {"section": "Persona", "key": "POST_MAX_TOKENS", "type": "int",
     "label": "Loop influencer: token massimi",
     "hint": "Tetto della risposta del modello per un post (didascalia + eventuale prompt immagine).",
     "default": "200"},
    {"section": "Persona", "key": "FEED_SKETCH_PER_DAY", "type": "int",
     "label": "Sketch al giorno per persona",
     "hint": "Quanti sketch (job immagine leggero per il Mac) il loop accoda al massimo per persona in un giorno. Lo sketch accompagna il post quando ha un'idea d'immagine.",
     "default": "4"},
    {"section": "Persona", "key": "DREAM_LOOP_ENABLED", "type": "bool",
     "label": "Sogno notturno attivo",
     "hint": "true: a intervalli le due influencer sognano (una scena + uno sketch) e lo scrivono nel diario. Genera contenuti da solo: spento di default.",
     "default": "false"},
    {"section": "Persona", "key": "DREAM_LOOP_INTERVAL_S", "type": "int",
     "label": "Sogni: distanza minima (s)",
     "hint": "Distanza minima fra due sogni. 7200 = due ore.",
     "default": "7200"},
    {"section": "Persona", "key": "DREAM_PER_AUTHOR_PER_DAY", "type": "int",
     "label": "Sogni giornalieri per sorella",
     "hint": "Tetto persistente per Anna e Aurora; un riavvio non lo azzera.",
     "default": "2"},
    {"section": "Persona", "key": "DREAM_IDLE_S", "type": "int",
     "label": "Sogni: inattività richiesta (s)",
     "hint": "Fuori dalla notte, sogna solo dopo questo tempo senza messaggi. 10800 = 3 ore.",
     "default": "10800"},
    {"section": "Persona", "key": "DREAM_NIGHT_START_HOUR", "type": "int",
     "label": "Sogni: inizio notte",
     "hint": "Ora locale di inizio della finestra notturna.",
     "default": "0"},
    {"section": "Persona", "key": "DREAM_NIGHT_END_HOUR", "type": "int",
     "label": "Sogni: fine notte",
     "hint": "Ora locale di fine della finestra notturna.",
     "default": "8"},

    # ── Canali esterni: chat/privati di una piattaforma che il CP non raggiunge
    # Il driver del canale tira le decisioni da /channel/* e pubblica l'esito.
    # Guida: docs/channel.md
    {"section": "Canali esterni", "key": "CHANNEL_CLIENTS", "type": "password",
     "label": "Token dei canali",
     "hint": "Elenco nella forma \"cam4=<token>;cb=<token>\": un token di almeno 32 caratteri per canale. Senza questa voce nessuna route /channel/* risponde (fail-closed), come per MCP. Genera con: python -c \"import secrets; print(secrets.token_hex(32))\".",
     "default": ""},
    {"section": "Canali esterni", "key": "CHANNEL_OPERATOR", "type": "str",
     "label": "Operatore (chi è \"io\")",
     "hint": "Nome autore dell'operatore senza @ (il driver manda from.username), più alias separati da virgola: nel dialogo interno diventa \"(io)\", entra fra chi può chiedere le immagini (insieme a CHANNEL_CERCHIA), in privato riceve la voce intima del documento (compagna sensuale) e con la banda intima accende il livello esplicito (docs/comfyui.md). Vuota = nessun creatore.",
     "default": ""},
    {"section": "Canali esterni", "key": "CHANNEL_CERCHIA", "type": "str",
     "label": "Cerchia (le muse, chi ha il livello)",
     "hint": "Handle senza @, separati da virgola: sono la banda intima del documento — la stessa che Instagram assegna a musa contando i messaggi (30), qui dichiarata a mano perché sul canale l'identità è solo l'handle. Chi è in questa riga ha la stessa apertura del creatore sulla vetrina (nudità ed esplicito fuori dal negativo, quando il documento li dichiara), può chiedere immagini come lui e in privato riceve la voce della musa; il quadro (`adult`, `virtual`) lo scrive il sistema. Vuota = il livello resta del solo operatore.",
     "default": ""},
    {"section": "Canali esterni", "key": "CHANNEL_VIP", "type": "str",
     "label": "VIP (glamour e lingerie)",
     "hint": "Handle senza @, separati da virgola: possono chiedere ritratti di Anna in lingerie sexy e stile glamour. Nudo ed erotismo esplicito restano riservati alle MUSA e al creatore.",
     "default": ""},
    {"section": "Canali esterni", "key": "CHANNEL_ENABLED", "type": "bool",
     "label": "Canali attivi",
     "hint": "false chiude tutte le route /channel/* senza cancellare i token.",
     "default": "true"},
    {"section": "Canali esterni", "key": "CHANNEL_MODEL", "type": "str",
     "label": "Modello dei canali",
     "hint": "Modello che scrive nelle chat dei canali. Vuoto = modello di default del control-plane. In una stanza conviene un modello piccolo e veloce: le risposte sono una battuta.",
     "default": ""},
    {"section": "Canali esterni", "key": "CHANNEL_CONTEXT_MESSAGES", "type": "int",
     "label": "Messaggi nel contesto",
     "hint": "Quanti degli ultimi messaggi della stanza entrano nel prompt. Alzalo se il bot \"non ricorda\" cosa si è detto due battute fa; abbassalo se il modello perde il filo (più contesto, meno attenzione su ognuno). Vale subito.",
     "default": "20"},
    {"section": "Canali esterni", "key": "CHANNEL_CONTEXT_CHARS", "type": "int",
     "label": "Caratteri per messaggio",
     "hint": "Troncamento di ogni messaggio nel contesto: evita che un singolo papiro saturi il prompt. Vale subito.",
     "default": "400"},
    {"section": "Canali esterni", "key": "CHANNEL_NUM_CTX", "type": "int",
     "label": "Finestra di contesto (token)",
     "hint": "Finestra chiesta al modello (num_ctx). Senza, Ollama usa il suo default (spesso 4096) e taglia l'INIZIO del prompt: identità e confini sono lì dentro. 8192 è prudente; su una macchina piccola abbassala, altrimenti alzala.",
     "default": "8192"},
    {"section": "Canali esterni", "key": "CHANNEL_MIN_REPLY_INTERVAL_S", "type": "int",
     "label": "Intervallo minimo fra risposte (s)",
     "hint": "Il control-plane non genera una nuova risposta prima di questi secondi dall'ultima: è il freno che evita di parlare addosso alla stanza.",
     "default": "25"},
    {"section": "Canali esterni", "key": "CHANNEL_REPLY_PROBABILITY", "type": "float",
     "label": "Probabilità di rispondere",
     "hint": "1.0 = risponde sempre quando il batch è maturo; valori più bassi ogni tanto lasciano correre (stesso effetto del vecchio PROB_RISPOSTA_BATCH, ma deciso dal CP).",
     "default": "1.0"},
    {"section": "Canali esterni", "key": "CHANNEL_FLOOD_MAX", "type": "int",
     "label": "Messaggi per raffica",
     "hint": "Oltre questo numero di messaggi dalla stessa persona nella finestra di raffica, l'autore viene segnato come spam. Non punisce da solo: conta gli strike.",
     "default": "6"},
    {"section": "Canali esterni", "key": "CHANNEL_STRIKE_MUTE", "type": "int",
     "label": "Strike per il mute",
     "hint": "Strike (violazioni ravvicinate) a cui il control-plane chiede al driver di silenziare l'autore. Al primo colpo non si punisce: si smette solo di rispondere.",
     "default": "2"},
    {"section": "Canali esterni", "key": "CHANNEL_STRIKE_BAN", "type": "int",
     "label": "Strike per il ban",
     "hint": "Strike a cui il control-plane chiede al driver di espellere l'autore. Gli strike decadono da soli dopo 30 minuti senza nuove violazioni.",
     "default": "3"},
]
